sudo: required
dist: bionic
language: java
jdk:
- openjdk10

install: true

script:
- mvn -q clean install  -Dmaven.test.skip=true -Dmaven.wagon.http.ssl.insecure=true -Dmaven.wagon.http.ssl.allowall=true
